### ISSUE TITLE
Move to wagtail-nest

### ISSUE THREAD

**Issue by zerolab** [wagtail-nest/wagtail-bakery#78]
Hey folks,

We are moving third-party packages to https://github.com/wagtail-nest
Could someone with admin rights, initiate the move for this package?

Thank you

**Comment by loicteixeira** [comment]
Ping @gasman @thibaudcolas @tomdyson 🙏

**Comment by gasman** [comment]
Done!

**Comment by loicteixeira** [comment]
Thank you @gasman.
Something I did not anticipate though, is that I cannot seem to be able to merge PRs anymore, I imagine I need to be added to the wagtail-nest org or something? Maybe he same can be done for @Stormheg which often works on this repo.

**Comment by zerolab** [comment]
uh-oh, forgot about that. Added you as an admin @loicteixeira, and @Stormheg as maintainer

**Comment by loicteixeira** [comment]
Perfect thank you
